### ISSUE TITLE
CloudFront needs to whitelist Origin

### ISSUE THREAD

**Issue by danypoudrier** [awslabs/speke-reference-server#3]
The installation worked fine.
 
However, I had issues with my player regarding CORS with FireFox and Chrome on MacOS. The issue was that the Origin header wasn’t whitelisted and was causing issues on the client player side because this header was not sent when cached.

The cloudformation template for CloudFront needs to be updated to whitelist the header Origin (see below)

![image](https://user-images.githubusercontent.com/39312183/41470119-a26bf89e-707d-11e8-895e-c0b69306cde1.png)

**Comment by JimTharioAmazon** [comment]
Hi there! Thanks for the report. I was able to recreate the CORS problem. I dug into it this week and took a different approach with maybe the same outcome. I added a CORS configuration to the key cache bucket and that seems to clear up the problem. CloudFront passes the CORS headers along from the bucket. If you have a moment, can you try the latest template and let me know your results?

**Comment by JimTharioAmazon** [comment]
Closing. Please reopen or open a new bug if we still have a problem here.
