### ISSUE TITLE
I Found redundant processing

### ISSUE THREAD

**Issue by OdaDaisuke** [awslabs/speke-reference-server#31]
`ContentProtectionData` is defined at here https://github.com/awslabs/speke-reference-server/blob/master/src/key_server_common.py#L93

and removed at here https://github.com/awslabs/speke-reference-server/blob/master/src/key_server_common.py#L96

Widevine( edef8ba9-79d6-4ace-a3c8-27dcd51d21ed ) don't need `ContentProtectionData`.

**Comment by JimTharioAmazon** [comment]
Merged pull request, tested and deployed an updated build. A couple of a dependencies versions were updated too.
