### ISSUE TITLE
Stuck at `CREATE_IN_PROGRESS` when creating CFn stack.

### ISSUE THREAD

**Issue by OdaDaisuke** [awslabs/speke-reference-server#33]
I can't create CFn stack. CFn just stuck in `CREATE_IN_PROGRESS`.

### Reproduce

I referenced this installtion instruction to setup CFn stack at `ap-northeast-1` region. https://github.com/awslabs/speke-reference-server/blob/b19f8ceb0b35135fc8dbe1bf39a41cc5d2f9595e/INSTALL.md

Can you reproduce this issue?

Don't you need to use `cfn-response` for CFn's lifecycle?

eg(key_server.py)↓

```
import cfnresponse
...
try:
  if event['RequestType'] == 'Delete' or event['RequestType'] == 'Create': 
    cfnresponse.send(event, context, cfnresponse.SUCCESS, {})
...
```

**Comment by OdaDaisuke** [comment]
@JimTharioAmazon help..

**Comment by OdaDaisuke** [comment]
I found strange log below in the cloud trail log(GetRolePolicy event).

```
...
"errorCode": "NoSuchEntityException",
"errorMessage": "The role policy with name MediaPackageInvokeSPEKEPolicy cannot be found.",
...
```

**Comment by JimTharioAmazon** [comment]
I just installed https://s3.amazonaws.com/rodeolabz-us-east-1/speke/speke_reference.json into us-west-2 and ap-northeast-1 following instructions in INSTALL.md. No problems encountered. You will need to wait at least 20-30 minutes for the CloudFront distribution to complete deploying. The actual time varies depending on the region and time of day.

**Comment by OdaDaisuke** [comment]
Resolved!
Thanks to advise.
