### ISSUE TITLE
Run source through PEP8 for style and other conventions

### ISSUE THREAD

**Issue by JimTharioAmazon** [awslabs/speke-reference-server#6]
10+ potential violations from previous releases.
Please re-run and review results.
Try pycharm.

**Comment by B-Souty** [comment]
Hi, I can have a look at this, I use pycharm and its "Inspect code..." function on my own scripts. Just to confirm, you want to run all .py file through the check?  or just some specific ones?

**Comment by JimTharioAmazon** [comment]
Hi, thanks for helping! Yes, the goal is to have all the .py source files follow PEP8 conventions. I honestly don't know the impact yet.

**Comment by JimTharioAmazon** [comment]
Thanks for the help with this one. I also added an autopep8 script to the project for future clean-ups.
