### ISSUE TITLE
Bump Python runtime from 3.6 to >= 3.7

### ISSUE THREAD

**Issue by thomas-alias-zaiko** [awslabs/speke-reference-server#75]
Hi!

I believe you are still using Python 3.6 as runtime for the Lambda function:
https://github.com/awslabs/speke-reference-server/blob/master/cloudformation/speke_reference.json#L249

Do you have any plan to bump Python's runtime from 3.6 to anything from **3.7 onwards**?

AWS Lambda is **deprecating** Python 3.6 fully on Aug 17th, 2022:
https://docs.aws.amazon.com/lambda/latest/dg/runtime-support-policy.html 

This means that the existing function there won't be updatable (can still invoke is safely.)
Also, creating won't be possible anymore.

Thank you in advance for your answer!

**Comment by mikedizon** [comment]
judging by the milestones, it doesn't seem like this project is actively being maintained.

**Comment by yufegao** [comment]
The Python runtime version is upgraded to 3.9.
